Support Python 3.9.2+ (#121)
Without this, an exception will be thrown `AttributeError: '_EnumDict' object has no attribute '_cls_name'`

Refs: https://github.com/python/cpython/commit/aba12b67c18b17bb727a0d50dd0653e38cb64dc8

This [line](https://github.com/python/cpython/blob/3.9/Lib/enum.py#L97) expects attribute `_cls_name`.